project:
  type: website
  
website:
  title: "ELSTE Data Science Master Course"
  description: "An introduction to data science using Python"
  page-navigation: true

  search:
    location: sidebar
  # navbar:
  #   right:
  #     - icon: github
  #       href: https://github.com/e5k/Data-Science/blob/main/_quarto.yml
  sidebar:
    style: "floating"
    title: "ELSTE Data Science Course"   # ðŸ‘ˆ moves site title here
    tools:     
      - icon: github
        href: ttps://github.com/e5k/Data-Science/
        text: "GitHub"
    background: "#F5F5F5"
    search: true
    contents: 
      - index.qmd
      - section: "Class 1"
        contents:
          - class1/day1-1_intro.qmd
          - class1/day1-2_pandas.qmd
          - class1/day1-3_data_exploration.qmd
          - class1/day1-4_queries.qmd
          - class1/day1-5_filtering.qmd
          - class1/day1-6_operations.qmd
          - class1/day1-summary.qmd
      - section: "Appendices"
        contents:
          - appendices/setup_vscode.qmd
      - references.qmd
  page-footer:
    background: "#F5F5F5"
    center: "Â© 2025 - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.en) - SÃ©bastien Biass & StÃ©phane Guerrier"
  # navbar:
  #   right:
  #     - icon: github
  #       href: https://github.com/
  #       aria-label: GitHub
bibliography: references.bib



format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"
    toc: true          # enable TOC
    toc-depth: 3       # how many heading levels to include
    toc-location: right
    toc-title: "On this page"
    toc-expand: 1      # how much to auto-expand initially
  # pdf:
  #   documentclass: scrreprt
  # revealjs: default # slides output


